#!/bin/bash
#
# ragnar-firstboot.sh — per-device finalisation for the "Ragnar OS" SD-card image
#
# A pre-built image is, by definition, identical on every card. Anything that
# must be unique per device, or that can only be known once real hardware is
# running, cannot be baked in — it has to happen the first time that particular
# device boots. That is this script, run once by ragnar-firstboot.service
# (oneshot, ordered Before=ragnar.service) and then disabled so it never runs
# again.
#
# It does nothing on a normal `install_ragnar.sh` install — the installer never
# enables the unit. It only exists on devices flashed from the Ragnar OS image.
#
# What it finalises:
#   * Unique SSH host keys     (a baked image would otherwise ship one key set)
#   * Per-device Ragnar TLS cert (regenerated by Ragnar at runtime; we only make
#                                 sure a baked one is cleared so it is unique)
#   * Optional /boot/firmware/ragnar.conf: hostname + display driver
#   * Optional /boot/firmware/ragnar-mesh.conf: join the Tailscale mesh
#   * rfkill unblock (also covered by a udev rule; belt and braces)
#
# Everything is idempotent and best-effort: a failure here must never stop the
# device from booting into the web UI.

set -u

RAGNAR_USER="ragnar"
RAGNAR_PATH="/home/${RAGNAR_USER}/Ragnar"
STAMP="/var/lib/ragnar/firstboot.done"
LOG_TAG="ragnar-firstboot"

log() { logger -t "$LOG_TAG" -- "$*" 2>/dev/null; echo "[$LOG_TAG] $*"; }

# Locate the FAT boot partition (differs across Pi OS versions).
boot_dir() {
    for d in /boot/firmware /boot; do
        [ -d "$d" ] && { echo "$d"; return 0; }
    done
    echo "/boot"
}
BOOT="$(boot_dir)"

# Already finalised? Do nothing (covers a manual re-enable of the unit).
if [ -f "$STAMP" ]; then
    log "Already finalised ($STAMP present) — nothing to do"
    exit 0
fi

log "First boot — finalising this device"
log "Board: $(tr -d '\0' < /proc/device-tree/model 2>/dev/null || echo unknown)"

# ── 1. Unique SSH host keys ────────────────────────────────────────────────
# The image build strips host keys; regenerate them here so every device has
# its own. (Harmless if OpenSSH already regenerated them on first boot.)
if command -v sshd >/dev/null 2>&1 || command -v ssh-keygen >/dev/null 2>&1; then
    if ! ls /etc/ssh/ssh_host_*_key >/dev/null 2>&1; then
        log "Generating unique SSH host keys"
        ssh-keygen -A >/dev/null 2>&1 || log "ssh-keygen -A failed (non-fatal)"
    fi
fi

# ── 2. Per-device Ragnar TLS certificate ───────────────────────────────────
# Ragnar generates certs/ragnar.{crt,key} on first run if they are absent. If a
# cert somehow got baked into the image, remove it so this device gets its own.
if [ -f "$RAGNAR_PATH/certs/ragnar.key" ]; then
    log "Clearing baked TLS cert so this device regenerates its own"
    rm -f "$RAGNAR_PATH/certs/ragnar.key" "$RAGNAR_PATH/certs/ragnar.crt" 2>/dev/null || true
fi

# ── 3. Optional config drop-in: /boot/firmware/ragnar.conf ──────────────────
# A plain key=value file the operator can drop onto the FAT partition before
# first boot (editable on any computer, no login needed). Recognised keys:
#   hostname=<name>      set the device hostname
#   display=<driver>     enable a screen (e.g. epd2in13_V4, gc9a01, ili9486,
#                        ssd1306, lcd1602) — switches the service to display mode
CONF="$BOOT/ragnar.conf"
[ -f "$CONF" ] || CONF="/boot/ragnar.conf"

CONF_HOSTNAME=""
CONF_DISPLAY=""
if [ -f "$CONF" ]; then
    log "Reading operator config: $CONF"
    # Parse conservatively: key=value, ignore comments/whitespace, no eval.
    while IFS='=' read -r key val; do
        key="$(echo "$key" | tr -d '[:space:]')"
        val="$(echo "$val" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^"//' -e 's/"$//')"
        case "$key" in
            ''|\#*) ;;
            hostname) CONF_HOSTNAME="$val" ;;
            display)  CONF_DISPLAY="$val" ;;
        esac
    done < "$CONF"
fi

# ── 3a. Hostname ────────────────────────────────────────────────────────────
if [ -n "$CONF_HOSTNAME" ]; then
    log "Setting hostname to '$CONF_HOSTNAME'"
    if command -v hostnamectl >/dev/null 2>&1; then
        hostnamectl set-hostname "$CONF_HOSTNAME" 2>/dev/null || true
    else
        echo "$CONF_HOSTNAME" > /etc/hostname
    fi
    # Keep /etc/hosts in step so sudo and local name resolution stay quiet.
    if grep -qE '^127\.0\.1\.1' /etc/hosts 2>/dev/null; then
        sed -i "s/^127\.0\.1\.1.*/127.0.1.1\t$CONF_HOSTNAME/" /etc/hosts
    else
        echo -e "127.0.1.1\t$CONF_HOSTNAME" >> /etc/hosts
    fi
fi

# ── 3b. Display driver ──────────────────────────────────────────────────────
# The image ships headless by default (safe: never seizes SPI/GPIO on a board
# whose pins drive a built-in panel). Enabling a screen means: record the driver
# in Ragnar's config AND switch the systemd unit off the headless entrypoint.
if [ -n "$CONF_DISPLAY" ]; then
    # Delegate to the shared mode-switch helper (same code the web UI and the AP
    # onboarding portal use). We run before ragnar.service has started, so no
    # restart is needed — the chosen mode is live on first start.
    if [ -f "$RAGNAR_PATH/scripts/set_display_mode.sh" ]; then
        bash "$RAGNAR_PATH/scripts/set_display_mode.sh" display "$CONF_DISPLAY" --no-restart \
            || log "Could not switch to display mode for '$CONF_DISPLAY'"
    else
        log "set_display_mode.sh missing — cannot enable display '$CONF_DISPLAY'"
    fi
fi

# ── 4. Mesh (Tailscale) first-boot provisioning ─────────────────────────────
# If the operator dropped a mesh config onto the boot partition, join now — this
# is the real device with real network and a real identity, which the chroot
# image build never had.
if [ -f "$BOOT/ragnar-mesh.conf" ] || [ -f /boot/ragnar-mesh.conf ]; then
    if [ -x "$RAGNAR_PATH/scripts/setup_mesh.sh" ]; then
        log "Mesh config found — provisioning Tailscale"
        bash "$RAGNAR_PATH/scripts/setup_mesh.sh" provision >/dev/null 2>&1 \
            || log "Mesh provisioning reported a problem (retry from the web UI)"
    fi
fi

# ── 5. Radios ───────────────────────────────────────────────────────────────
command -v rfkill >/dev/null 2>&1 && rfkill unblock all 2>/dev/null || true

# ── 6. Finalise — stamp and disable so this never runs again ────────────────
mkdir -p "$(dirname "$STAMP")"
date -u +%Y-%m-%dT%H:%M:%SZ > "$STAMP" 2>/dev/null || touch "$STAMP"
systemctl disable ragnar-firstboot.service >/dev/null 2>&1 || true
log "First-boot finalisation complete"
exit 0
